name: SharpSoft.App CD

# https://bitplatform.dev/templates/dev-ops

env:
  API_SERVER_ADDRESS: 'https://kingforce.sharpsoftco.com/'
  APP_SERVICE_NAME: 'app-service-bp-test'
  IOS_CODE_SIGN_PROVISION: 'SharpSoft.App'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  
  build_blazor_hybrid_android:
    name: build blazor hybrid (android)
    runs-on: ubuntu-latest
  
    steps:
     
    - name: Checkout source code
      uses: actions/checkout@v4
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - uses: actions/setup-node@v4
      with:
        node-version: 20
  
    - name: Extract Android signing key from env
      uses: timheuer/base64-to-file@v1.2
      with:
          fileDir: './src/Client/SharpSoft.App.Client.Maui/'
          fileName: 'SharpSoft.App.keystore'
          encodedString: ${{ secrets.ANDROID_RELEASE_KEYSTORE_FILE_BASE64 }}
  
    - name: Update appsettings.json api server address
      uses: devops-actions/variable-substitution@v1.2 
      with:
        files: 'src/Client/SharpSoft.App.Client.Core/appsettings.json'
      env:
        ApiServerAddress: ${{ env.API_SERVER_ADDRESS }}

    - name: Install maui
      run: cd src && dotnet workload install maui-android

    - name: Install Android Sdk platform tools
      run: ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools"
  
    - name: Generate CSS/JS files
      run: |
          dotnet build src/Client/SharpSoft.App.Client.Core/SharpSoft.App.Client.Core.csproj -t:BeforeBuildTasks --no-restore
          dotnet build src/Client/SharpSoft.App.Client.Maui/SharpSoft.App.Client.Maui.csproj -t:BeforeBuildTasks --no-restore
  
    - name: Build aab
      run: dotnet build src/Client/SharpSoft.App.Client.Maui/SharpSoft.App.Client.Maui.csproj -c Release -p:AndroidPackageFormat=aab -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="SharpSoft.App.keystore" -p:AndroidSigningKeyAlias=SharpSoft.App -p:AndroidSigningKeyPass="${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.ANDROID_RELEASE_SIGNING_PASSWORD }}" -f net8.0-android
  
    - name: Build apk
      run: dotnet build src/Client/SharpSoft.App.Client.Maui/SharpSoft.App.Client.Maui.csproj -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="SharpSoft.App.keystore" -p:AndroidSigningKeyAlias=SharpSoft.App -p:AndroidSigningKeyPass="${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.ANDROID_RELEASE_SIGNING_PASSWORD }}" -f net8.0-android
  
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-bundle
        path: src/Client/SharpSoft.App.Client.Maui/bin/Release/net8.0-android/*-Signed.*

  
