name: SharpSoft.App CI

# https://bitplatform.dev/templates/dev-ops

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:

  build_blazor_server:
    name: build blazor
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Android Sdk platform tools
      run: ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools"
      
    - name: Install wasm
      run: cd src && dotnet workload install wasm-tools wasm-experimental
      
    - name: Install maui
      run: cd src && dotnet workload install maui-android
    - name: Build
      run: dotnet build SharpSoft.App.sln -c Release
